openapi: 3.0.3
info:
  title: Basic Bike API
  description: API for bike rental for Basic Bike
  version: 1.0.0
servers:
  - url: 'https://example.com'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Bike:
      type: object
      required:
        - id
        - bikeId
        - isRented
        - rentStartTime
      properties:
        id:
          type: integer
          format: int64
        bikeId:
          type: string
        isRented:
          type: boolean
        rentStartTime:
          type: string
    Bikes:
      type: array
      items:
        $ref: "#/components/schemas/Bike"
    RentRequest:
      type: object
      required:
        - renterId
        - rentStartTime
      properties:
        renterId:
          type: string
        rentStartTime:
          type: string

paths:
  /bikes:
    get:
      summary: Returns a list of available bikes.
      description: >
        Bikes returned are physical bikes. Each bike is identified by bike ID,
        prefixed with BB. The prefix is the current convention and may change over
        time.
        
        To protect privacy, the renter ID is not returned. Only status of rental
        and start time are returned.
      responses:
        '200':
          description: JSON Array of bikes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bikes"
  /bikes/{id}:
    get:
      summary: Return info about bike matches the given ID.
      description: >
        The information about bike with given ID.
        
        To protect privacy, the renter ID is not returned. Only status of rental
        and start time are returned.
      responses:
        '200':
          description: JSON object of bike
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bike"
    post:
      summary: Rent the bike by giving renter ID and start time.
      description: >
        To rent bike, user must provide ID and starting time of renting.
        
        Since the API is intended for staffs, we allow users to specify time manually.
      responses:
        '200':
          description: Status of renting
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /token:
    post:
      summary: Get API token for usage.
      description: >
        Users must provide username and password of BasicBike to get token that can be
        used in requests.
        
        The token must be in the Authorization header.
      responses:
        '200':
          description: Token of the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string


